apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine
  name: alpine
  namespace: qq9
spec:
  containers:
    - image: alpine:edge
      name: alpine
      command: ["sh", "-c", "while true; do echo 'Hello Alpine'; sleep 3; done"]
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
