apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    app: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MONGO_INITDB_ROOT_PASSWORD
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: vol
          mountPath: /etc/mongo
      - name: mongo-express
        image: mongo-express:1.0.2-20-alpine3.19
        env:
          - name: ME_CONFIG_MONGODB_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: ME_CONFIG_MONGODB_URL
          - name: ME_CONFIG_BASICAUTH
            valueFrom:
              configMapKeyRef:
                name: config
                key: ME_CONFIG_BASICAUTH
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: ME_CONFIG_MONGODB_ADMINUSERNAME
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: ME_CONFIG_MONGODB_ADMINPASSWORD
        ports:
        - containerPort: 8081
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc