apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server      
  labels:
    app: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.18  
        ports:
        - containerPort: 80