apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: qq5
  labels:
    app: drupal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:10.2.7-php8.2-fpm-bookworm
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-svc
  namespace: qq5
spec:
  selector:
    app: drupal
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer