apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-cm
data:
  ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
  ME_CONFIG_BASICAUTH: "false"

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  MONGO_INITDB_ROOT_USERNAME: ""
  MONGO_INITDB_ROOT_PASSWORD: ""
  ME_CONFIG_MONGODB_ADMINUSERNAME: ""
  ME_CONFIG_MONGODB_ADMINPASSWORD: ""

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_INITDB_ROOT_USERNAME

            name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_INITDB_ROOT_PASSWORD

      - name: mongo-express
        image: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-express-cm
                key: ME_CONFIG_MONGODB_URL

            name: ME_CONFIG_BASICAUTH
            valueFrom:
              configMapKeyRef:
                name: mongo-express-cm
                key: ME_CONFIG_BASICAUTH

            name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: ME_CONFIG_MONGODB_ADMINUSERNAME

            name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret