apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: qq3
  labels:
    app: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0.20-rc3-nanoserver-1809
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-mongo
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mongo
              key: MONGO_INITDB_ROOT_PASSWORD
      - name: mongo-express
        image: mongo-express:1.0.2-20-alpine3.19
        env:
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: configset 
              key: ME_CONFIG_MONGODB_URL
        - name: ME_CONFIG_BASICAUTH
          valueFrom:
            configMapKeyRef:
              name: configset
              key: ME_CONFIG_BASICAUTH
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: secret-mongo
              key: ME_CONFIG_MONGODB_ADMINUSERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mongo
              key: ME_CONFIG_MONGODB_ADMINPASSWORD

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: configset
data:
  ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
  ME_CONFIG_BASICAUTH: "false"

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-mongo
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "root"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
  ME_CONFIG_MONGODB_ADMINPASSWORD: "root"